# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_remove_recipe_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='targetNicotine',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
