# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0008_auto_20170528_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pgRatio',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='targetAmount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='targetNicotine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vgRatio',
        ),
    ]
