# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_auto_20170527_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='percentage',
        ),
    ]
