# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0010_auto_20170528_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
